version: "3"

services:
  database:
    container_name: 42stats-db
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - 42stats_database:/var/lib/mysql
    networks:
      - 42stats_network
    restart: always

  phpmyadmin:
    container_name: 42stats-phpmyadmin
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    depends_on:
      - database
    environment:
      PMA_ARBITRARY: ${PMA_ARBITRARY}
      PMA_HOST: ${PMA_HOST}
      UPLOAD_LIMIT: 10000000000
    ports:
      - 5050:80
    networks:
      - 42stats_network
    restart: always

  # api:
  #   container_name: 42stats-api
  #   image: 42stats-api
  #   platform: linux/amd64
  #   build:
  #     context: ../../api
  #     dockerfile: dev.Dockerfile
  #   environment:
  #     VITE_API_URL: ${VITE_API_URL}
  #     CLIENT_URL: ${CLIENT_URL}
  #     DATABASE_URL: ${DATABASE_URL}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #     FORTY_TWO_UID: ${FORTY_TWO_UID}
  #     FORTY_TWO_SECRET: ${FORTY_TWO_SECRET}
  #   depends_on:
  #     - database
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ../../api:/app
  #     - ~/.m2:/root/.m2
  #   networks:
  #     - 42stats_network
  #   restart: always

  backend:
    container_name: 42stats-backend
    image: 42stats-backend
    build:
      context: ../../backend
      dockerfile: dev.Dockerfile
    environment:
      VITE_API_URL: ${VITE_API_URL}
      CLIENT_URL: ${CLIENT_URL}
      MYSQL_DB_URL: ${MYSQL_DB_URL}
    depends_on:
      - database
    ports:
      - 3000:3000
    volumes:
      - ../../backend:/app
      - /app/node_modules
    networks:
      - 42stats_network
    restart: always

  # client:
  #   container_name: 42stats-client
  #   image: 42stats-client
  #   build:
  #     context: ../../client
  #     dockerfile: dev.Dockerfile
  #   environment:
  #     VITE_API_URL: ${VITE_API_URL}
  #   depends_on:
  #     - api
  #   ports:
  #     - 5173:5173
  #   volumes:
  #     - ../../client:/app
  #     - /app/node_modules
  #   networks:
  #     - 42stats_network
  #   restart: always

networks:
  42stats_network:
    name: 42stats_network

volumes:
  42stats_database:
    name: 42stats_database
