-- CREATE TABLE IF NOT EXISTS user (
--   id INT AUTO_INCREMENT PRIMARY KEY,
--   username VARCHAR(255) NOT NULL,
--   email VARCHAR(255) NOT NULL UNIQUE,
-- );

-- CREATE TABLE IF NOT EXISTS forty_two_campus (
--   id INT AUTO_INCREMENT PRIMARY KEY,
--   name VARCHAR(255) NOT NULL,
--   country VARCHAR(255) NOT NULL,
--   user_count INT NOT NULL
-- )

-- CREATE TABLE IF NOT EXISTS forty_two_user (
--   id INT AUTO_INCREMENT PRIMARY KEY,
--   email VARCHAR(255) UNIQUE NOT NULL,
--   login VARCHAR(255) UNIQUE NOT NULL,
--   first_name VARCHAR(255) NOT NULL,
--   last_name VARCHAR(255) NOT NULL,
--   image VARCHAR(255),
--   pool_month VARCHAR(255),
--   pool_year VARCHAR(255),
--   level FLOAT NOT NULL,
--   campus_id INT NOT NULL,
--   FOREIGN KEY (campus_id) REFERENCES forty_two_campus(id)
-- )
