import { Footer } from "@/components/layouts/footer/Footer";
import { Header } from "@/components/layouts/header/Header";
import { AuthProvider } from "@/hooks/useAuth";
import { ThemeProvider } from "@/lib/ThemeProvider";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import * as React from "react";
import { Suspense } from "react";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "42stats",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`min-h-screen flex flex-col ${GeistSans.className}`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <AuthProvider>
            <Header />
            <Suspense>{children}</Suspense>
            <Footer />
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
