import { Footer } from "@/components/layouts/Footer";
import { Header } from "@/components/layouts/header/Header";
import { AuthProvider } from "@/hooks/useAuth";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "42stats",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`min-h-screen flex flex-col ${GeistSans.className}`}>
        <AuthProvider>
          <Header />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
