CREATE TABLE IF NOT EXISTS "user" (
  id INT NOT NULL PRIMARY KEY,
  login VARCHAR(255) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  image VARCHAR(255) DEFAULT NULL,
  pool_month VARCHAR(255) NOT NULL,
  pool_year VARCHAR(255) NOT NULL,
  level DOUBLE PRECISION NOT NULL,
  campus_id INT NOT NULL,
  blackholed BOOLEAN NOT NULL,
  CONSTRAINT fk_campus_id FOREIGN KEY (campus_id) REFERENCES campus(id)
  ON DELETE CASCADE
  ON UPDATE CASCADE
);
