CREATE TABLE IF NOT EXISTS `external_credentials` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `provider` VARCHAR(255) NOT NULL UNIQUE,
  `client_id` VARCHAR(255) NOT NULL,
  `client_secret` TEXT NOT NULL,
  `expires_at` DATETIME NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
